dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

addons:
  chrome: stable

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  directories:
     - ./node_modules

install:
  - yarn install

script:
  - yarn run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - yarn run e2e -- --protractor-config=e2e/protractor-ci.conf.js
